import type { GetServerSideProps, NextPage } from 'next';
import React from 'react';
import Head from 'next/head';
import { Container } from 'components/ui/Container';
import { profileEditMap } from 'public/data';
import Button from '@material-ui/core/Button';
import { NEXT_SERVER } from 'config';
import { User, UserEdit } from 'types/user';
import { useSelector } from 'react-redux';
import { selectLogin } from 'lib/redux/login/loginSlice';
import { useRouter } from 'next/dist/client/router';
import { fetchUserList } from 'lib/apis/user';

interface Props {
  userList: User[];
}

const User: NextPage<Props> = ({ userList }: { userList: User[] }) => {
  const { login } = useSelector(selectLogin);
  const [userProfile, setUserProfile] = React.useState<UserEdit>({
    name: '',
    grade: '',
    gender: '',
  });
  const route = useRouter();

  const onChange = (e: any) => {
    const { name, value } = e.target;
    setUserProfile({
      ...userProfile,
      [name]: value,
    });
  };

  const postUser = async (userProfile: UserEdit) => {
    const res = await fetch(`${NEXT_SERVER}/v1/user/post`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(userProfile),
    });
    if (!res.ok) {
      return alert('학생 추가 실패');
    }

    setUserProfile({
      name: '',
      grade: '',
      gender: '',
    });
    route.replace(route.asPath);
    return alert('학생 추가 성공');
  };

  const handleUserDelete = async (userId: string) => {
    const res = await fetch(`${NEXT_SERVER}/v1/user/post?id=${userId}`, {
      method: 'DELETE',
      headers: { 'content-type': 'application/json' },
    });
    if (!res.ok) {
      return alert('학생 삭제하지 못했습니다.');
    }
    route.replace(route.asPath);
    return alert('학생을 삭제했습니다.');
  };

  React.useEffect(() => {
    if (!login) {
      route.replace('/login');
    }
  }, []);
  return (
    <>
      <Head>
        <title>학생 추가</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div className="grid grid-cols-2 pt-8 px-6 text-left">
          <div>
            <h2 className="pt-16 pb-8">학생 정보 추가</h2>
            {profileEditMap.map((edit, idx) => {
              return (
                <div className="pb-4" key={idx}>
                  <div className="pb-4">{edit.tit}</div>
                  {!edit.data ? (
                    <input
                      name={edit.name}
                      value={userProfile[edit.name]}
                      type={edit.type}
                      onChange={onChange}
                    />
                  ) : (
                    edit.data.map((e, idx) => {
                      return (
                        <span className="pr-4" key={idx}>
                          <span>{e.value}</span>
                          <input
                            type={edit.type}
                            name={edit.name}
                            value={e.value}
                            onChange={onChange}
                          />
                        </span>
                      );
                    })
                  )}
                </div>
              );
            })}
            <Button
              onClick={() => {
                if (userProfile.name !== '') {
                  postUser(userProfile);
                }
              }}>
              추가
            </Button>
          </div>
          <div>
            <h2 className="pt-16 pb-8">학생 정보 삭제</h2>
            <div>
              {userList.map((user) => {
                return (
                  <div className="flex pb-2 justify-between" key={user.name}>
                    <div>
                      <span>
                        <b>{user.name}</b>
                      </span>{' '}
                      <span>{user.grade}</span>
                    </div>
                    <span
                      onClick={() => {
                        const result = confirm(
                          `${user.name}학생을 삭제하시겠습니까?`,
                        );
                        if (result) {
                          handleUserDelete(user._id);
                        }
                      }}>
                      <a>삭제</a>
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </Container>
    </>
  );
};

export default User;

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      userList: (await fetchUserList()) as User[],
    },
  };
};
