import Button from '@material-ui/core/Button';
import { UserList } from 'components/main';
import fetchUserList from 'lib/apis/user';
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { User } from 'types/user';
import { Container } from '../components/ui/Container';

interface Props {
  users: User[];
}

const Main: NextPage<Props> = ({ users }: { users: User[] }) => {
  return (
    <>
      <Head>
        <title>솔잎샘 학원</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h2 className="pt-16">Welcome to</h2>
        <div>
          <Button>학생관리</Button>
          <Button>오답관리</Button>
          <Button></Button>
        </div>
        <UserList users={users} />
      </Container>
    </>
  );
};

export default Main;

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      users: (await fetchUserList()) as User[],
    },
  };
};
