import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import type { NextPage } from 'next';
import { Container } from 'components/ui/Container';

import Button from '@material-ui/core/Button';

import { User } from 'types/user';
import { useRouter } from 'next/dist/client/router';
import { BASE_URL } from 'config';
import { useDispatch, useSelector } from 'react-redux';
import {
  selectUser,
  setSelectedUser,
  setSelectedUserId,
} from 'lib/redux/user/userSlice';
import { studentMenu } from 'public/data';
import { Wrapper } from 'components/student';

interface Props {}

const Student: NextPage<Props> = () => {
  const { selectedUserId, selectedUser, users } = useSelector(selectUser);

  const dispatch = useDispatch();
  const route = useRouter();

  const { pages } = route.query;

  const onChange = async (e: React.ChangeEvent<HTMLSelectElement>) => {
    dispatch(setSelectedUserId(e.target.value));
    route.push(`/student/${e.target.value}?pages=1`);
  };
  React.useEffect(() => {
    if (selectedUserId !== '') {
      route.push(`${BASE_URL}/student/${selectedUserId}?pages=1`);
    }
  }, []);

  return (
    <>
      <Head>
        <title>{route.pathname}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <div className="flex justify-between pt-20 pb-4">
          <select value={selectedUserId} onChange={onChange}>
            {users?.map((user, idx) => {
              return (
                <option key={idx} value={user._id}>
                  {user.name}
                </option>
              );
            })}
          </select>
          <div>
            {studentMenu.map((menu, idx) => {
              return (
                <Link
                  key={idx}
                  href={`${BASE_URL}/student/${
                    selectedUserId !== '' ? selectedUserId : users[0]._id
                  }?pages=${menu.code}`}>
                  <a>
                    <Button
                      style={{
                        color: `${pages === menu.code ? 'blue' : 'black'}`,
                      }}>
                      <b>{menu.name}</b>
                    </Button>
                  </a>
                </Link>
              );
            })}
          </div>
        </div>
        <Wrapper></Wrapper>
      </Container>
    </>
  );
};

export default Student;
